/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './App.{js,jsx,ts,tsx}',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        primary: '#FF6B35',
        'primary-light': '#FFB399',
        'primary-dark': '#D64423',
        secondary: '#004E89',
        'secondary-light': '#1982C4',
        background: '#FFFFFF',
        'background-dark': '#F5F5F5',
        'background-darker': '#EFEFEF',
        text: '#333333',
        'text-light': '#666666',
        'text-lighter': '#999999',
        'text-inverse': '#FFFFFF',
        success: '#4CAF50',
        warning: '#FFC107',
        error: '#F44336',
        info: '#2196F3',
        border: '#E0E0E0',
        disabled: '#CCCCCC',
      },
      spacing: {
        xs: 4,
        sm: 8,
        md: 12,
        lg: 16,
        xl: 20,
        '2xl': 24,
        '3xl': 32,
      },
      borderRadius: {
        xs: 4,
        sm: 8,
        md: 12,
        lg: 16,
        xl: 20,
      },
      fontSize: {
        xs: 12,
        sm: 14,
        md: 16,
        lg: 18,
        xl: 20,
        '2xl': 24,
        '3xl': 28,
      },
      fontWeight: {
        light: '300',
        normal: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
        extrabold: '800',
      },
      boxShadow: {
        sm: '0 1px 2px rgba(0,0,0,0.1)',
        md: '0 2px 6px rgba(0,0,0,0.12)',
        lg: '0 4px 12px rgba(0,0,0,0.15)',
      },
    },
  },
  plugins: [],
};
